### ISSUE TITLE
Compile locally

### ISSUE THREAD

**Issue by quinnhornblow** [duckdb-wasm-examples/sveltekit-typescript#1]
Excited to get duckdb up and running so thanks for this example. I'm running into errors when I try to use your example in a locally compiled app (i.e npm run dev), particularly with the web-worker and importing the duckdb-wasm modules. Are you able to provide an example that is targeted for local builds and not a github static site? Thanks

**Comment by bmschmidt** [comment]
Sorry for not seeing this comment. The version here should work with `npm run dev` right now, although I would love to see any problems if it is not building for you.
